markdown: kramdown

title: Brain Soup

description: Personal site of a funny, failed artist.

logo: https://res.cloudinary.com/dqmzgagnv/image/upload/v1633006385/bslogo_gkpjni.png

url: https://www.brainsoup.me

author:
  name: Egg

plugins:
  - jekyll-paginate-v2
  - jekyll-seo-tag

pagination:
  enabled: true
  debug: true
  collection: 'posts'
  per_page: 5
  permalink: '/:num/'
  sort_field: "date"
  sort_reverse: true
    
permalink: /:title/

excerpt_separator: "<!--more-->"

defaults:
    -
      scope:
        path: ""
        type: "posts"
      values:
        layout: "post"
        comments: true

livereload: BOOL

twitter:
  username: anarelaxis

exclude:
  - sass