reCaptcha:
  siteKey: 6LcNBmccAAAAAKvSqFQk5J1UxK0mUPUgUxYYkbow
  secret: rC2rXmarDl0qaJuBfoPqbaobSpdRbC9Y2w6dmc1OCbwf43CIRh5endUpwLy6wuq+kQpNs0J3XOmiTiXv33P+tv3US2s8X4p45chOX5JFDnKsXckuR2RnKkVjcnZ+NLRr1ubjKeJhqUOCrqWIn1NfcV+0U9Kgo1J8Sdbm0e/sEDCNuub1pGqt3Hju0bHRzl37ZtWguQ9MlN7NOMkzaFol0knyqAU/Y/lWtGDcGkXORXF9cl6LbKUOILkkt1WyaBiWVNPOJrPwyxFs4JUhYQzReaCoixuFhprKyYNckrs4Ur/SUsvyv1mcO/isx2sYrw2LWSeze3HCLmlbbArEUPhup+SsMTFS+Ohc2i6C4kFSP7d3hwMIHPZV7P3yWjFIVaw1Q0eAKyrRklJnKVTysAmE1Ii/ekPSi/1XrQe1nf6zxhYJ2yVH5gIg69L47p/aM7X4cVaFVbLfCuJXHx+931SKbGbd4LxDgBlDGBFU1+jgr2CBpNgLsm53ZRHWtoVUAWQVicVJQdRHXdTjrS0Poc3isQ0mmXda5QO+BZXYAXz9lv+B3vIocaD8csUc18zkWylTpMIpNoaK1kIqLMXI/Q2CRHOy4IJi0OMXMKMuuvfxjdFvz2h8CBbkQIF0BGWwmVnlVkIn5wVMM3FK+TYtHiz5tTAFMtQgTfIowwuZ/rNwBZE=

markdown: kramdown
kramdown:
  input: GFM
title: Brain Soup
plugins:
  - jekyll-paginate

paginate: 4
paginate_path: "/blog/page:num/"
permalink: pretty
