markdown: kramdown
kramdown:
  input: GFM
title: Brain Soup
plugins:
  - jekyll-paginate

paginate: 4
paginate_path: "/blog/page:num/"
permalink: /:categories/:title
defaults:
    -
      scope:
        path: ""
        type: "posts"
      values:
        layout: "post"
        comments: false
reCaptcha:
  siteKey: 6LcNBmccAAAAAKvSqFQk5J1UxK0mUPUgUxYYkbow
  secret: 6LdI-GccAAAAAIOkHUyRfKWn0zMlUwjpYbuiT6k4
