markdown: kramdown
kramdown:
  input: GFM
title: Brain Soup
plugins:
  - jekyll-paginate

paginate: 4
paginate_path: "/blog/page:num/"
permalink: /:categories/:title
defaults:
    -
      scope:
        path: ""
        type: "posts"
      values:
        layout: "post"
        comments: false

staticman_url: https://eggsstaticmaninstance.herokuapp.com/v2/entry/eggsrepos/brainsoup/master/comments
