reCaptcha:
  siteKey: 6LcNBmccAAAAAKvSqFQk5J1UxK0mUPUgUxYYkbow
  secret: S02h9GCuQj7ICut2Tev3MegUjFpXqLSHYzG/X8ftqH/L7RFBaj8Fr0xu6OITO2MOcz2lF1baylXKcKU+pUAf+xSpZewKrnJs5FymFR+KVz/JnBMzilpzVRh1xUFTE5mQAPlmn2GUu0Mp99MI2qk1Lj6zwqYaRVdDayXEZji1Q/TopKZ5WHMmvK++79ZVyWR26tMJbWpiUY+26u5wa088kWCLurctL7mns5mGnbJg9W+07PdpwFNyPC2dNEPD44RgU5Z0pbA/XtMni0/DACnNm6BMBC1EmOGrbKIAPjLoymffQb4lKTkzdxB5PU6bbg8wJp61UaK6dc2eQE2ZSLhqXQq1M/Y3ZFuLzvRxoaUDBniHZD3EoM4AfevnswMT09fA9eWsEgvl4Sku7qRnw8iLMO29R6IJkT2hGrWIlgpaH9B6rVXRhsutioVGokjYo0BWDtfLEUPl86XB6/RZBVraRWF33xvoepEoV385h12fY0dLAjplY264LJ4fZCZq5rl3tXQCXG5EoowXX70JmLMTpPWEFR4ufl9VLF5a4B2ElEdUpI6cpuJE62Xcz+n41lZsclZku0QTsKrAyBLKa5rJUDZwAbQc6VKUWWGPw/SM5LLU8fmjY+DNQtPdbH8ROJksHwSzCYfuOqfQgNYO+COaIFAqsatJ+ykhSfg/V//yEGw=

markdown: kramdown
kramdown:
  input: GFM
title: Brain Soup
plugins:
  - jekyll-paginate

paginate: 4
paginate_path: "/blog/page:num/"
permalink: pretty
